version: '2'

services:
  myapp:
    image: 'docker.io/bitnami/symfony:1-debian-10'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - MARIADB_DATABASE=bitnami_myapp
    depends_on:
      - mariadb
      - mercure
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=bitnami_myapp
  client:
    build:
      context: ./client
      target: react-client
    depends_on:
      - mercure
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
  mercure:
    build:
      context: ./mercure
      target: mercure_hub
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
